### ISSUE TITLE
Add setup files for existing synApps releases

### ISSUE THREAD

**Issue by ralphlange** [epics-base/ci-scripts#15]
Add setup files that are named after synApps releases and contain the correct set of module versions that were used for that synApps release.

Use case: allow compiling a module against dependency versions "like in synApps x.y".

**Comment by anjohnson** [comment]
Another use case would be to specify a synApps release version but also allow individual module versions to be overridden, so "like in synApps x.y but with MCA at version m.n". Hopefully this is trivial to do and it might not be used much, but it reflects real-world usage of synApps.

**Comment by ralphlange** [comment]
Any setting in a setup file can always be overridden from the job spec in .travis.yml - so that use case is included at no extra cost.
Really, the only work is finding out the version numbers and creating the setup files.
