### ISSUE TITLE
Rebuild dependency chain if a module has changed

### ISSUE THREAD

**Issue by ralphlange** [epics-base/ci-scripts#18]
If a module in the cache is found to be outdated, not only that module has to be rebuilt (as it is done now), but the complete remaining chain of dependencies needs to be rebuilt to make sure the whole set of dependencies is consistent.

**Comment by tboegi** [comment]
Work in progress (not yet a PR)
https://github.com/EuropeanSpallationSource/ci-scripts/commit/a546f1561dd885c79ce43d7eaf42cb24339d4d8e

**Comment by ralphlange** [comment]
It's only the *remaining* chain that has to be rebuilt on change.

E.g., if the dependency modules are "BASE ASYN MOTOR", an update of ASYN should cause MOTOR to be rebuilt (behind ASYN in the chain), but not BASE (in front of ASYN).
