### ISSUE TITLE
Add ability to install msi for R3.14 builds

### ISSUE THREAD

**Issue by MJGaughran** [epics-base/ci-scripts#20]
The msi utility is not available as part of EPICS R3.14.

Existing Travis configurations manually install this utility, for example in:
https://github.com/epics-modules/iocStats/blob/70128c77ad97529726adc0c3c590241067e7db9f/.ci/travis-prepare.sh

This should be made available as part of the standard prepare.sh script, for certain versions of EPICS Base.

**Comment by mdavidsaver** [comment]
It's not clear to me how to take advantage of this change.  My 3.14 build has `$(MSI)` expanding to `msi` which is not in `$PATH`.  Should add-msi-to-314.patch be setting something like `MSI = $(EPICS_BASE_BIN)/msi` to configure/CONFIG_BASE?

https://github.com/epics-base/epics-base/blob/3.14/configure/CONFIG_BASE#L115-L117

**Comment by ralphlange** [comment]
Meh.
Somehow I thought that putting it in the BASE_BIN would suffice. Shoot.

Caught me adding a feature untested. Hm. I haven't used MSI for a decade and was too lazy to add a test. No justification, not even a good explanation. Duh.
