### ISSUE TITLE
CACHEDIR=~/.cache interferes with other applications

### ISSUE THREAD

**Issue by ralphlange** [epics-base/ci-scripts#22]
On behalf of @tboegi:
Inside a regular user account (that uses a graphical environment), the CACHEDIR setting of `~/.cache` is being used by other applications. This usually works, but makes it hard to delete the ci-scripts parts when testing locally.

**Comment by tboegi** [comment]
﻿Please have a look here:
﻿https://github.com/epics-base/ci-scripts/pull/23
