### ISSUE TITLE
Add more detail to Appveyor docs

### ISSUE THREAD

**Issue by MarkRivers** [epics-base/ci-scripts#37]
ci-scripts is great, it really was quite painless to get CI working on both Linux and Windows!

It would have helped me to have a little more information in this document:
https://github.com/epics-base/ci-scripts/blob/master/appveyor/README.md
In Step 1 of How to Use These Scripts it refers one to the Appveyor documentation.
https://www.appveyor.com/docs/

Step 2 of that appveyor.com document does not really match what I saw once I logged into Appveyor using my Github credentials.  I needed to chose between using the Appveyor App on Github, or some other option (I forget what, but it started with "O").  I was not sure which to select.  It's really a weakness on the Appveyor doc page, but it would be nice to explain those options, and also how to add the Github repository you want to build, on this page:
https://github.com/epics-base/ci-scripts/blob/master/appveyor/README.md

**Comment by ralphlange** [comment]
Please check the new version of the README on the master branch of my fork [here](https://github.com/ralphlange/ci-scripts/tree/master/appveyor).
I will push those to the main repo in the next days unless I hear objections.

**Comment by MarkRivers** [comment]
That looks good, thanks.
