### ISSUE TITLE
Run 'make clean' on dependencies to reduce cache size

### ISSUE THREAD

**Issue by ralphlange** [epics-base/ci-scripts#48]
From @mdavidsaver:

Dependencies that are kept fully uncleaned take up considerable size (easily >5GB for EPICS 7 and some extra modules) that might cause trouble with services.

Running 'make clean' after compiling dependency modules is an easy way to shrink the required cache size.
It might be useful to add a global env setting to switch off that cleaning step.

**Comment by anjohnson** [comment]
You could even build the modules with INSTALL_LOCATION set and not archive their sources either, just save the install tree. This saves having to do the `make clean` step.

**Comment by ralphlange** [comment]
Interesting option.

**Comment by ralphlange** [comment]
Stats:
On the Travis ci-scripts CI itself (~35 jobs; non-recursive base and sequencer), the total cache size for branch master was reduced from ~7GB to ~2.4GB. Time savings are negligible (~4 out of 70 minutes).
