### ISSUE TITLE
Add support for builds on GitLab CI/CD 

### ISSUE THREAD

**Issue by ralphlange** [epics-base/ci-scripts#51]
Suggested by @tboegi:

Please support the GitLab CI/CD service.

**Comment by ralphlange** [comment]
@tboegi:
I have created a [mirror project on GitLab](https://gitlab.com/ralphlange/ci-scripts) to be able to properly run the `ci-scripts` tests.
My development branch is [`devel/gitlab` in my fork](https://github.com/ralphlange/ci-scripts/tree/devel/gitlab).

Can you provide a minimal `.gitlab-ci.yml` (or whatever it is called) configuration file to get me started?

**Comment by tboegi** [comment]
The one that is in use here, is found there:
https://github.com/EuropeanSpallationSource/m-epics-ethercatmc/blob/master/.gitlab-ci.yml

However, I did not put any effort into it, so it is guaranteed to have
bugs introduced by copy-paste.
A code-review is needed, help welcome.
The good thing is, that it passes the runs here...
