### ISSUE TITLE
GHA deprecates ubuntu-16.04

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/ci-scripts#62]
Looks like GHA will be removing the ubuntu image we're using to test with older GCC.

https://github.com/actions/virtual-environments/issues/3287

> ... we will remove Ubuntu 16.04 on September 20, 2021.

**Comment by mdavidsaver** [comment]
ppa:ubuntu-toolchain-r/test for ubuntu-18.04 (bionic) [currently has](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=bionic) GCC 9, 10, and 11.

**Comment by mdavidsaver** [comment]
Since our goal is really continued support for the likely long lived RHEL/Centos 7, maybe the goal should be to switch to some kind of container build.  I've [played](https://github.com/mdavidsaver/build-epics/blob/2b1851e045835d64297a3f55d868d9575d142703/.github/workflows/ci-build.yml#L40) with docker in this context.  It works, but isn't so transparent.  Perhaps some clever person has written an action which can conditionally execute via docker.

**Comment by ralphlange** [comment]
As I have mentioned in one of the last Telecons:
ci-scripts supports GitLab CI/CD, which runs all jobs in any Docker container that is available on Dockerhub.

**Comment by mdavidsaver** [comment]
I think the situation wrt. ubuntu-16.04 has now been addressed.
