### ISSUE TITLE
hooks for main module

### ISSUE THREAD

**Issue by kmpeters** [epics-base/ci-scripts#68]
I see that there is a mechanism for specifying hooks for dependencies in the github-actions YAML file.  What is the recommended approach for patching/configuring the main module?  It looks like creating new steps in the YAML file is the only option right now.

Motivation: motor driver modules don't build example IOCs by default (https://github.com/epics-motor/motorVMC/blob/234094bc9ea47c472d9600799d926934712c0317/configure/CONFIG_SITE#L39); it is usually enabled by creating a CONFIG_SITE.local file based on the example (https://github.com/epics-motor/motorVMC/blob/234094bc9ea47c472d9600799d926934712c0317/configure/EXAMPLE_CONFIG_SITE.local#L8).

**Comment by ralphlange** [comment]
That's correct.

I added the hooks for the dependencies as they are being installed from inside the `cue.py` script and there is no way to get something done for a specific dependency from the YAML level.
For the main module, you can directly run your hook script from the YAML.
