### ISSUE TITLE
extra2 does not work

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-base/ci-scripts#75]
Parameters passed to `extra2` or higher seem to be ignored. Only `extra` and `extra1` work.

**Comment by dirk-zimoch** [comment]
Maybe `extra` should actually be a list:
```
      extra:
        - CMD_CPPFLAGS=....
        - CMD_CXXFLAGS=....
        - XXX=xxxx
        - YYY=yyyy
```

**Comment by mdavidsaver** [comment]
`$(matrix.extra)` is being used to set an environment variable (a string).  I don't know how this will handle an array.

```yaml
  env:
    - EXTRA: "$(matrix.extra)"
```

**Comment by ralphlange** [comment]
The code in `cue.py` handling extra arguments is:
```
    # Add EXTRA make arguments
    for tag in ['EXTRA', 'EXTRA1', 'EXTRA2', 'EXTRA3', 'EXTRA4', 'EXTRA5']:
        val = os.environ.get(tag, "")
        if len(val)>0:
            extra_makeargs.append(val)
```
I don't see how that would treat the first two other than the remaining four variables.

Could it be that your setting the variables through the YAML config only works for EXTRA and EXTRA1?

**Comment by dirk-zimoch** [comment]
That is the default in .github/workflows/ci-scripts-build.yml. Michael showed me where I have to add `EXTRA2` in addition to `extra2`. I find that cubersome. One more reason to allow lists in `extra`.
